# Score thresholds for recognition.
score_thresholds = {
	"i_am_a_bunny_book"                  : 0.15,
	"laugh_out_loud_joke_book"           : 0.3 ,
	"scotch_bubble_mailer"               : 0.15,
	"up_glucose_bottle"                  : 0.3 ,
	"dasani_water_bottle"                : 0.25,
	"rawlings_baseball"                  : 0.3 ,
	"folgers_classic_roast_coffee"       : 0.3 ,
	"elmers_washable_no_run_school_glue" : 0.1 ,
	"hanes_tube_socks"                   : 0.1,
	"womens_knit_gloves"                 : 0.3 ,
	"cherokee_easy_tee_shirt"            : 0.3 ,
	"peva_shower_curtain_liner"          : 0.3 ,
	"cloud_b_plush_bear"                 : 0.1,
	"barkely_hide_bones"                 : 0.15,
	"kyjen_squeakin_eggs_plush_puppies"  : 0.3,
	"cool_shot_glue_sticks"              : 0.15,
	"creativity_chenille_stems"          : 0.2 ,
	"soft_white_lightbulb"               : 0.25,
	"safety_first_outlet_plugs"          : 0.1,
	"oral_b_toothbrush_red"              : 0.1 ,
	"oral_b_toothbrush_green"            : 0.1 ,
	"dr_browns_bottle_brush"             : 0.3 ,
	"command_hooks"                      : 0.5 ,
	"easter_turtle_sippy_cup"            : 0.15,
	"fiskars_scissors_red"               : 0.15,
	"scotch_duct_tape"                   : 0.5 ,
	"woods_extension_cord"               : 0.15,
	"platinum_pets_dog_bowl"             : 0.1 ,
	"fitness_gear_3lb_dumbbell"          : 0.15,
	"rolodex_jumbo_pencil_cup"           : 0.1 ,
	"clorox_utility_brush"               : 0.3 ,
	"kleenex_paper_towels"               : 0.15,
	"expo_dry_erase_board_eraser"        : 0.15,
	"kleenex_tissue_box"                 : 0.3 ,
	"ticonderoga_12_pencils"             : 0.3 ,
	"crayola_24_ct"                      : 0.5 ,
	"jane_eyre_dvd"                      : 0.1 ,
	"dove_beauty_bar"                    : 0.15,
	"staples_index_cards"                : 0.3 ,
}


